LevelDataPointersLo:
      ; Level 1-1
      .BYTE <LevelData_1_1_Area0
      .BYTE <LevelData_1_1_Area1
      .BYTE <LevelData_1_1_Area2
      .BYTE <LevelData_1_1_Area3
      .BYTE <LevelData_1_1_Area4
      .BYTE <LevelData_1_1_Area5
      .BYTE <LevelData_1_1_Area5
      .BYTE <LevelData_1_1_Area5
      .BYTE <LevelData_1_1_Area5
      .BYTE <LevelData_1_1_Area5
      ; Level 1-2
      .BYTE <LevelData_1_2_Area0
      .BYTE <LevelData_1_2_Area1
      .BYTE <LevelData_1_2_Area2
      .BYTE <LevelData_1_2_Area3
      .BYTE <LevelData_1_2_Area4
      .BYTE <LevelData_1_3_Area0
      .BYTE <LevelData_1_3_Area0
      .BYTE <LevelData_1_3_Area0
      .BYTE <LevelData_1_3_Area0
      .BYTE <LevelData_1_3_Area0
      ; Level 1-3
      .BYTE <LevelData_1_3_Area0
      .BYTE <LevelData_1_3_Area1
      .BYTE <LevelData_1_3_Area2
      .BYTE <LevelData_1_3_Area3
      .BYTE <LevelData_1_3_Area4
      .BYTE <LevelData_1_3_Area4
      .BYTE <LevelData_1_3_Area4
      .BYTE <LevelData_1_3_Area4
      .BYTE <LevelData_1_3_Area4
      .BYTE <LevelData_1_3_Area4
      ; Level 2-1
      .BYTE <LevelData_2_1_Area0
      .BYTE <LevelData_2_1_Area1
      .BYTE <LevelData_2_1_Area4
      .BYTE <LevelData_2_1_Area4
      .BYTE <LevelData_2_1_Area3
      .BYTE <LevelData_2_1_Area4
      .BYTE <LevelData_2_1_Area4
      .BYTE <LevelData_2_1_Area4
      .BYTE <LevelData_2_1_Area4
      .BYTE <LevelData_2_1_Area4
      ; Level 2-2
      .BYTE <LevelData_2_2_Area0
      .BYTE <LevelData_2_2_Area1
      .BYTE <LevelData_2_2_Area2
      .BYTE <LevelData_2_2_Area3
      .BYTE <LevelData_2_2_Area4
      .BYTE <LevelData_2_2_Area5
      .BYTE <LevelData_2_2_Area5
      .BYTE <LevelData_2_2_Area5
      .BYTE <LevelData_2_2_Area5
      .BYTE <LevelData_2_2_Area5
      ; Level 2-3
      .BYTE <LevelData_2_3_Area0
      .BYTE <LevelData_2_3_Area1
      .BYTE <LevelData_2_3_Area2
      .BYTE <LevelData_2_3_Area3
      .BYTE <LevelData_2_3_Area4
      .BYTE <LevelData_2_3_Area5
      .BYTE <LevelData_2_3_Area6
      .BYTE <LevelData_2_3_Area7
      .BYTE <LevelData_2_3_Area7
      .BYTE <LevelData_2_3_Area7
      ; Level 3-1
      .BYTE <LevelData_3_1_Area0
      .BYTE <LevelData_3_1_Area1
      .BYTE <LevelData_3_1_Area2
      .BYTE <LevelData_3_1_Area3
      .BYTE <LevelData_3_1_Area4
      .BYTE <LevelData_3_2_Area0
      .BYTE <LevelData_3_2_Area0
      .BYTE <LevelData_3_2_Area0
      .BYTE <LevelData_3_2_Area0
      .BYTE <LevelData_3_2_Area0
      ; Level 3-2
      .BYTE <LevelData_3_2_Area0
      .BYTE <LevelData_3_2_Area1
      .BYTE <LevelData_3_2_Area2
      .BYTE <LevelData_3_3_Area0
      .BYTE <LevelData_3_3_Area0
      .BYTE <LevelData_3_3_Area0
      .BYTE <LevelData_3_3_Area0
      .BYTE <LevelData_3_3_Area0
      .BYTE <LevelData_3_3_Area0
      .BYTE <LevelData_3_3_Area0
      ; Level 3-3
      .BYTE <LevelData_3_3_Area0
      .BYTE <LevelData_3_3_Area1
      .BYTE <LevelData_3_3_Area2
      .BYTE <LevelData_3_3_Area3
      .BYTE <LevelData_3_3_Area4
      .BYTE <LevelData_3_3_Area5
      .BYTE <LevelData_3_3_Area6
      .BYTE <LevelData_3_3_Area7
      .BYTE <LevelData_3_3_Area8
      .BYTE <LevelData_3_3_Area8
      ; Level 4-1
      .BYTE <LevelData_4_1_Area0
      .BYTE <LevelData_4_1_Area1
      .BYTE <LevelData_4_2_Area0
      .BYTE <LevelData_4_2_Area0
      .BYTE <LevelData_4_2_Area0
      .BYTE <LevelData_4_2_Area0
      .BYTE <LevelData_4_2_Area0
      .BYTE <LevelData_4_2_Area0
      .BYTE <LevelData_4_2_Area0
      .BYTE <LevelData_4_2_Area0
      ; Level 4-2
      .BYTE <LevelData_4_2_Area0
      .BYTE <LevelData_4_2_Area1
      .BYTE <LevelData_4_2_Area2
      .BYTE <LevelData_4_2_Area3
      .BYTE <LevelData_4_2_Area4
      .BYTE <LevelData_4_2_Area4
      .BYTE <LevelData_4_2_Area4
      .BYTE <LevelData_4_2_Area4
      .BYTE <LevelData_4_2_Area4
      .BYTE <LevelData_4_2_Area4
      ; Level 4-3
      .BYTE <LevelData_4_3_Area0
      .BYTE <LevelData_4_3_Area1
      .BYTE <LevelData_4_3_Area2
      .BYTE <LevelData_4_3_Area3
      .BYTE <LevelData_4_3_Area4
      .BYTE <LevelData_4_3_Area5
      .BYTE <LevelData_4_3_Area6
      .BYTE <LevelData_4_3_Area7
      .BYTE <LevelData_5_1_Area0
      .BYTE <LevelData_5_1_Area0
      ; Level 5-1
      .BYTE <LevelData_5_1_Area0
      .BYTE <LevelData_5_1_Area1
      .BYTE <LevelData_5_1_Area2
      .BYTE <LevelData_5_2_Area0
      .BYTE <LevelData_5_2_Area0
      .BYTE <LevelData_5_2_Area0
      .BYTE <LevelData_5_2_Area0
      .BYTE <LevelData_5_2_Area0
      .BYTE <LevelData_5_2_Area0
      .BYTE <LevelData_5_2_Area0
      ; Level 5-2
      .BYTE <LevelData_5_2_Area0
      .BYTE <LevelData_5_2_Area1
      .BYTE <LevelData_5_2_Area2
      .BYTE <LevelData_5_2_Area3
      .BYTE <LevelData_5_2_Area4
      .BYTE <LevelData_5_2_Area5
      .BYTE <LevelData_5_3_Area0
      .BYTE <LevelData_5_3_Area0
      .BYTE <LevelData_5_3_Area0
      .BYTE <LevelData_5_3_Area0
      ; Level 5-3
      .BYTE <LevelData_5_3_Area0
      .BYTE <LevelData_5_3_Area1
      .BYTE <LevelData_5_3_Area2
      .BYTE <LevelData_5_3_Area3
      .BYTE <LevelData_5_3_Area4
      .BYTE <LevelData_5_3_Area5
      .BYTE <LevelData_5_3_Area5
      .BYTE <LevelData_5_3_Area5
      .BYTE <LevelData_5_3_Area5
      .BYTE <LevelData_5_3_Area5
      ; Level 6-1
      .BYTE <LevelData_6_1_Area0
      .BYTE <LevelData_6_1_Area1
      .BYTE <LevelData_6_1_Area2
      .BYTE <LevelData_6_1_Area3
      .BYTE <LevelData_6_1_Area4
      .BYTE <LevelData_6_1_Area5
      .BYTE <LevelData_6_1_Area6
      .BYTE <LevelData_6_1_Area6
      .BYTE <LevelData_6_1_Area6
      .BYTE <LevelData_6_1_Area6
      ; Level 6-2
      .BYTE <LevelData_6_2_Area0
      .BYTE <LevelData_6_2_Area1
      .BYTE <LevelData_6_2_Area2
      .BYTE <LevelData_6_2_Area2
      .BYTE <LevelData_6_2_Area2
      .BYTE <LevelData_6_2_Area2
      .BYTE <LevelData_6_2_Area2
      .BYTE <LevelData_6_2_Area2
      .BYTE <LevelData_6_2_Area2
      .BYTE <LevelData_6_2_Area2
      ; Level 6-3
      .BYTE <LevelData_6_3_Area0
      .BYTE <LevelData_6_3_Area1
      .BYTE <LevelData_6_3_Area2
      .BYTE <LevelData_6_3_Area3
      .BYTE <LevelData_6_3_Area4
      .BYTE <LevelData_6_3_Area5
      .BYTE <LevelData_6_3_Area6
      .BYTE <LevelData_6_3_Area6
      .BYTE <LevelData_6_3_Area6
      .BYTE <LevelData_6_3_Area6
      ; Level 7-1
      .BYTE <LevelData_7_1_Area0
      .BYTE <LevelData_7_1_Area1
      .BYTE <LevelData_7_1_Area2
      .BYTE <LevelData_7_1_Area3
      .BYTE <LevelData_7_1_Area4
      .BYTE <LevelData_7_1_Area5
      .BYTE <LevelData_7_1_Area5
      .BYTE <LevelData_7_1_Area5
      .BYTE <LevelData_7_1_Area5
      .BYTE <LevelData_7_1_Area5
      ; Level 7-2
      .BYTE <LevelData_7_2_Area0
      .BYTE <LevelData_7_2_Area1
      .BYTE <LevelData_7_2_Area2
      .BYTE <LevelData_7_2_Area3
      .BYTE <LevelData_7_2_Area4
      .BYTE <LevelData_7_2_Area5
      .BYTE <LevelData_7_2_Area6
      .BYTE <LevelData_7_2_Area7
      .BYTE <LevelData_7_2_Area8
      .BYTE <LevelData_7_2_Area9
      ; Level 7-3
      .BYTE <LevelData_7_3_Area0
      .BYTE <LevelData_7_3_Area0
      .BYTE <LevelData_7_3_Area0
      .BYTE <LevelData_7_3_Area0
      .BYTE <LevelData_7_3_Area0
      .BYTE <LevelData_7_3_Area0
      .BYTE <LevelData_7_3_Area0
      .BYTE <LevelData_7_3_Area0
      .BYTE <LevelData_7_3_Area0
      .BYTE <LevelData_7_3_Area0

LevelDataPointersHi:
      ; Level 1-1
      .BYTE >LevelData_1_1_Area0
      .BYTE >LevelData_1_1_Area1
      .BYTE >LevelData_1_1_Area2
      .BYTE >LevelData_1_1_Area3
      .BYTE >LevelData_1_1_Area4
      .BYTE >LevelData_1_1_Area5
      .BYTE >LevelData_1_1_Area5
      .BYTE >LevelData_1_1_Area5
      .BYTE >LevelData_1_1_Area5
      .BYTE >LevelData_1_1_Area5
      ; Level 1-2
      .BYTE >LevelData_1_2_Area0
      .BYTE >LevelData_1_2_Area1
      .BYTE >LevelData_1_2_Area2
      .BYTE >LevelData_1_2_Area3
      .BYTE >LevelData_1_2_Area4
      .BYTE >LevelData_1_3_Area0
      .BYTE >LevelData_1_3_Area0
      .BYTE >LevelData_1_3_Area0
      .BYTE >LevelData_1_3_Area0
      .BYTE >LevelData_1_3_Area0
      ; Level 1-3
      .BYTE >LevelData_1_3_Area0
      .BYTE >LevelData_1_3_Area1
      .BYTE >LevelData_1_3_Area2
      .BYTE >LevelData_1_3_Area3
      .BYTE >LevelData_1_3_Area4
      .BYTE >LevelData_1_3_Area4
      .BYTE >LevelData_1_3_Area4
      .BYTE >LevelData_1_3_Area4
      .BYTE >LevelData_1_3_Area4
      .BYTE >LevelData_1_3_Area4
      ; Level 2-1
      .BYTE >LevelData_2_1_Area0
      .BYTE >LevelData_2_1_Area1
      .BYTE >LevelData_2_1_Area4
      .BYTE >LevelData_2_1_Area4
      .BYTE >LevelData_2_1_Area3
      .BYTE >LevelData_2_1_Area4
      .BYTE >LevelData_2_1_Area4
      .BYTE >LevelData_2_1_Area4
      .BYTE >LevelData_2_1_Area4
      .BYTE >LevelData_2_1_Area4
      ; Level 2-2
      .BYTE >LevelData_2_2_Area0
      .BYTE >LevelData_2_2_Area1
      .BYTE >LevelData_2_2_Area2
      .BYTE >LevelData_2_2_Area3
      .BYTE >LevelData_2_2_Area4
      .BYTE >LevelData_2_2_Area5
      .BYTE >LevelData_2_2_Area5
      .BYTE >LevelData_2_2_Area5
      .BYTE >LevelData_2_2_Area5
      .BYTE >LevelData_2_2_Area5
      ; Level 2-3
      .BYTE >LevelData_2_3_Area0
      .BYTE >LevelData_2_3_Area1
      .BYTE >LevelData_2_3_Area2
      .BYTE >LevelData_2_3_Area3
      .BYTE >LevelData_2_3_Area4
      .BYTE >LevelData_2_3_Area5
      .BYTE >LevelData_2_3_Area6
      .BYTE >LevelData_2_3_Area7
      .BYTE >LevelData_2_3_Area7
      .BYTE >LevelData_2_3_Area7
      ; Level 3-1
      .BYTE >LevelData_3_1_Area0
      .BYTE >LevelData_3_1_Area1
      .BYTE >LevelData_3_1_Area2
      .BYTE >LevelData_3_1_Area3
      .BYTE >LevelData_3_1_Area4
      .BYTE >LevelData_3_2_Area0
      .BYTE >LevelData_3_2_Area0
      .BYTE >LevelData_3_2_Area0
      .BYTE >LevelData_3_2_Area0
      .BYTE >LevelData_3_2_Area0
      ; Level 3-2
      .BYTE >LevelData_3_2_Area0
      .BYTE >LevelData_3_2_Area1
      .BYTE >LevelData_3_2_Area2
      .BYTE >LevelData_3_3_Area0
      .BYTE >LevelData_3_3_Area0
      .BYTE >LevelData_3_3_Area0
      .BYTE >LevelData_3_3_Area0
      .BYTE >LevelData_3_3_Area0
      .BYTE >LevelData_3_3_Area0
      .BYTE >LevelData_3_3_Area0
      ; Level 3-3
      .BYTE >LevelData_3_3_Area0
      .BYTE >LevelData_3_3_Area1
      .BYTE >LevelData_3_3_Area2
      .BYTE >LevelData_3_3_Area3
      .BYTE >LevelData_3_3_Area4
      .BYTE >LevelData_3_3_Area5
      .BYTE >LevelData_3_3_Area6
      .BYTE >LevelData_3_3_Area7
      .BYTE >LevelData_3_3_Area8
      .BYTE >LevelData_3_3_Area8
      ; Level 4-1
      .BYTE >LevelData_4_1_Area0
      .BYTE >LevelData_4_1_Area1
      .BYTE >LevelData_4_2_Area0
      .BYTE >LevelData_4_2_Area0
      .BYTE >LevelData_4_2_Area0
      .BYTE >LevelData_4_2_Area0
      .BYTE >LevelData_4_2_Area0
      .BYTE >LevelData_4_2_Area0
      .BYTE >LevelData_4_2_Area0
      .BYTE >LevelData_4_2_Area0
      ; Level 4-2
      .BYTE >LevelData_4_2_Area0
      .BYTE >LevelData_4_2_Area1
      .BYTE >LevelData_4_2_Area2
      .BYTE >LevelData_4_2_Area3
      .BYTE >LevelData_4_2_Area4
      .BYTE >LevelData_4_2_Area4
      .BYTE >LevelData_4_2_Area4
      .BYTE >LevelData_4_2_Area4
      .BYTE >LevelData_4_2_Area4
      .BYTE >LevelData_4_2_Area4
      ; Level 4-3
      .BYTE >LevelData_4_3_Area0
      .BYTE >LevelData_4_3_Area1
      .BYTE >LevelData_4_3_Area2
      .BYTE >LevelData_4_3_Area3
      .BYTE >LevelData_4_3_Area4
      .BYTE >LevelData_4_3_Area5
      .BYTE >LevelData_4_3_Area6
      .BYTE >LevelData_4_3_Area7
      .BYTE >LevelData_5_1_Area0
      .BYTE >LevelData_5_1_Area0
      ; Level 5-1
      .BYTE >LevelData_5_1_Area0
      .BYTE >LevelData_5_1_Area1
      .BYTE >LevelData_5_1_Area2
      .BYTE >LevelData_5_2_Area0
      .BYTE >LevelData_5_2_Area0
      .BYTE >LevelData_5_2_Area0
      .BYTE >LevelData_5_2_Area0
      .BYTE >LevelData_5_2_Area0
      .BYTE >LevelData_5_2_Area0
      .BYTE >LevelData_5_2_Area0
      ; Level 5-2
      .BYTE >LevelData_5_2_Area0
      .BYTE >LevelData_5_2_Area1
      .BYTE >LevelData_5_2_Area2
      .BYTE >LevelData_5_2_Area3
      .BYTE >LevelData_5_2_Area4
      .BYTE >LevelData_5_2_Area5
      .BYTE >LevelData_5_3_Area0
      .BYTE >LevelData_5_3_Area0
      .BYTE >LevelData_5_3_Area0
      .BYTE >LevelData_5_3_Area0
      ; Level 5-3
      .BYTE >LevelData_5_3_Area0
      .BYTE >LevelData_5_3_Area1
      .BYTE >LevelData_5_3_Area2
      .BYTE >LevelData_5_3_Area3
      .BYTE >LevelData_5_3_Area4
      .BYTE >LevelData_5_3_Area5
      .BYTE >LevelData_5_3_Area5
      .BYTE >LevelData_5_3_Area5
      .BYTE >LevelData_5_3_Area5
      .BYTE >LevelData_5_3_Area5
      ; Level 6-1
      .BYTE >LevelData_6_1_Area0
      .BYTE >LevelData_6_1_Area1
      .BYTE >LevelData_6_1_Area2
      .BYTE >LevelData_6_1_Area3
      .BYTE >LevelData_6_1_Area4
      .BYTE >LevelData_6_1_Area5
      .BYTE >LevelData_6_1_Area6
      .BYTE >LevelData_6_1_Area6
      .BYTE >LevelData_6_1_Area6
      .BYTE >LevelData_6_1_Area6
      ; Level 6-2
      .BYTE >LevelData_6_2_Area0
      .BYTE >LevelData_6_2_Area1
      .BYTE >LevelData_6_2_Area2
      .BYTE >LevelData_6_2_Area2
      .BYTE >LevelData_6_2_Area2
      .BYTE >LevelData_6_2_Area2
      .BYTE >LevelData_6_2_Area2
      .BYTE >LevelData_6_2_Area2
      .BYTE >LevelData_6_2_Area2
      .BYTE >LevelData_6_2_Area2
      ; Level 6-3
      .BYTE >LevelData_6_3_Area0
      .BYTE >LevelData_6_3_Area1
      .BYTE >LevelData_6_3_Area2
      .BYTE >LevelData_6_3_Area3
      .BYTE >LevelData_6_3_Area4
      .BYTE >LevelData_6_3_Area5
      .BYTE >LevelData_6_3_Area6
      .BYTE >LevelData_6_3_Area6
      .BYTE >LevelData_6_3_Area6
      .BYTE >LevelData_6_3_Area6
      ; Level 7-1
      .BYTE >LevelData_7_1_Area0
      .BYTE >LevelData_7_1_Area1
      .BYTE >LevelData_7_1_Area2
      .BYTE >LevelData_7_1_Area3
      .BYTE >LevelData_7_1_Area4
      .BYTE >LevelData_7_1_Area5
      .BYTE >LevelData_7_1_Area5
      .BYTE >LevelData_7_1_Area5
      .BYTE >LevelData_7_1_Area5
      .BYTE >LevelData_7_1_Area5
      ; Level 7-2
      .BYTE >LevelData_7_2_Area0
      .BYTE >LevelData_7_2_Area1
      .BYTE >LevelData_7_2_Area2
      .BYTE >LevelData_7_2_Area3
      .BYTE >LevelData_7_2_Area4
      .BYTE >LevelData_7_2_Area5
      .BYTE >LevelData_7_2_Area6
      .BYTE >LevelData_7_2_Area7
      .BYTE >LevelData_7_2_Area8
      .BYTE >LevelData_7_2_Area9
      ; Level 7-3
      .BYTE >LevelData_7_3_Area0
      .BYTE >LevelData_7_3_Area0
      .BYTE >LevelData_7_3_Area0
      .BYTE >LevelData_7_3_Area0
      .BYTE >LevelData_7_3_Area0
      .BYTE >LevelData_7_3_Area0
      .BYTE >LevelData_7_3_Area0
      .BYTE >LevelData_7_3_Area0
      .BYTE >LevelData_7_3_Area0
      .BYTE >LevelData_7_3_Area0
